image: node:14

stages:
  - test
  - deploy

before_script:
  - npm install

cache:
  paths:
    - node_modules/

test:
  stage: test
  script:
    - npm run coverage
    - npm run lint
  artifacts:
    paths:
      - coverage

pages:
  stage: deploy
  script:
    - npm run doc
    - mv ./docs ./public
  artifacts:
    paths:
      - public
