"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.FunctionPlotSection = exports.PointsPlotSection = exports.PlotSection = exports.PlotManager = exports.Plot = exports.LineManager = exports.LineType = exports.Line = exports.ArcManager = exports.Direction = exports.Arc = exports.PointManager = exports.PointType = exports.GridManager = exports.Grid = exports.Point = exports.FunctionPlotManager = exports.FunctionPlot = exports.AxisManager = exports.Axis = void 0;
var components_1 = require("./components");
Object.defineProperty(exports, "Axis", { enumerable: true, get: function () { return components_1.Axis; } });
Object.defineProperty(exports, "AxisManager", { enumerable: true, get: function () { return components_1.AxisManager; } });
Object.defineProperty(exports, "FunctionPlot", { enumerable: true, get: function () { return components_1.FunctionPlot; } });
Object.defineProperty(exports, "FunctionPlotManager", { enumerable: true, get: function () { return components_1.FunctionPlotManager; } });
Object.defineProperty(exports, "Point", { enumerable: true, get: function () { return components_1.Point; } });
Object.defineProperty(exports, "Grid", { enumerable: true, get: function () { return components_1.Grid; } });
Object.defineProperty(exports, "GridManager", { enumerable: true, get: function () { return components_1.GridManager; } });
Object.defineProperty(exports, "PointType", { enumerable: true, get: function () { return components_1.PointType; } });
Object.defineProperty(exports, "PointManager", { enumerable: true, get: function () { return components_1.PointManager; } });
Object.defineProperty(exports, "Arc", { enumerable: true, get: function () { return components_1.Arc; } });
Object.defineProperty(exports, "Direction", { enumerable: true, get: function () { return components_1.Direction; } });
Object.defineProperty(exports, "ArcManager", { enumerable: true, get: function () { return components_1.ArcManager; } });
Object.defineProperty(exports, "Line", { enumerable: true, get: function () { return components_1.Line; } });
Object.defineProperty(exports, "LineType", { enumerable: true, get: function () { return components_1.LineType; } });
Object.defineProperty(exports, "LineManager", { enumerable: true, get: function () { return components_1.LineManager; } });
Object.defineProperty(exports, "Plot", { enumerable: true, get: function () { return components_1.Plot; } });
Object.defineProperty(exports, "PlotManager", { enumerable: true, get: function () { return components_1.PlotManager; } });
Object.defineProperty(exports, "PlotSection", { enumerable: true, get: function () { return components_1.PlotSection; } });
Object.defineProperty(exports, "PointsPlotSection", { enumerable: true, get: function () { return components_1.PointsPlotSection; } });
Object.defineProperty(exports, "FunctionPlotSection", { enumerable: true, get: function () { return components_1.FunctionPlotSection; } });
