"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PlotManager = exports.FunctionPlot = exports.PlotSection = exports.PointsPlot = exports.Plot = void 0;
var Plot_1 = require("./Plot");
Object.defineProperty(exports, "Plot", { enumerable: true, get: function () { return Plot_1.Plot; } });
var PointsPlot_1 = require("./PointsPlot");
Object.defineProperty(exports, "PointsPlot", { enumerable: true, get: function () { return PointsPlot_1.PointsPlot; } });
var PlotSection_1 = require("./PlotSection");
Object.defineProperty(exports, "PlotSection", { enumerable: true, get: function () { return PlotSection_1.PlotSection; } });
var FunctionPlot_1 = require("./FunctionPlot");
Object.defineProperty(exports, "FunctionPlot", { enumerable: true, get: function () { return FunctionPlot_1.FunctionPlot; } });
var PlotManager_1 = require("./PlotManager");
Object.defineProperty(exports, "PlotManager", { enumerable: true, get: function () { return PlotManager_1.PlotManager; } });
