"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PlotManager = exports.FunctionPlotSection = exports.PointsPlotSection = exports.PlotSection = exports.Plot = void 0;
var Plot_1 = require("./Plot");
Object.defineProperty(exports, "Plot", { enumerable: true, get: function () { return Plot_1.Plot; } });
Object.defineProperty(exports, "PlotSection", { enumerable: true, get: function () { return Plot_1.PlotSection; } });
Object.defineProperty(exports, "PointsPlotSection", { enumerable: true, get: function () { return Plot_1.PointsPlotSection; } });
Object.defineProperty(exports, "FunctionPlotSection", { enumerable: true, get: function () { return Plot_1.FunctionPlotSection; } });
var PlotManager_1 = require("./PlotManager");
Object.defineProperty(exports, "PlotManager", { enumerable: true, get: function () { return PlotManager_1.PlotManager; } });
